apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: vector
      username: vector
      port: 9000
      server: clickhouse
      tlsSkipVerify: false
    secureJsonData:
      password: vector

  - name: ElasticSearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: 'test'
      timeField: '@timestamp'
